nums=[1,2,3,4,5]
it=iter(nums)
# print(it.__next__())
# print(it.__next__())
# print(it.__next__())
# print(it.__next__())
# print(it.__next__())
print(next(it))
print(next(it))
print(next(it))
print(next(it))
print(next(it))
